MOCK_PROPERTIES = [
    {
        'id': 1,
        'location': [30.0125, 31.7513],
        'city': 'New Administrative Capital',
        'listing_type': 'buy',
        'price': '12,800,000 EGP',
        'imageUrl': 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800',
        'title': 'Luxury Villa in New Capital',
        'description': 'A stunning 5-bedroom villa with a private pool and spacious garden in the New Administrative Capital.',
        'contactEmail': 'sales@premiumestates.eg',
        'contactPhone': '+20 100 123 4567',
        'bedrooms': 5,
        'bathrooms': 4,
        'area': '450 sqm',
        'year_built': 2022,
        'tags': ['pool', 'private garden', 'smart home']
    },
    {
        'id': 2,
        'location': [30.1415, 31.6288],
        'city': 'El Shorouk',
        'listing_type': 'rent',
        'price': '45,000 EGP / Month',
        'imageUrl': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
        'title': 'Modern Apartment in El Shorouk',
        'description': 'Elegant 3-bedroom apartment with a view. Perfect for families looking for a quiet life in El Shorouk.',
        'contactEmail': 'rentals@cairoliving.com',
        'contactPhone': '+20 111 987 6543',
        'bedrooms': 3,
        'bathrooms': 2,
        'area': '180 sqm',
        'year_built': 2020,
        'tags': ['air conditioner', 'parking']
    },
    {
        'id': 3,
        'location': [30.1348, 31.7392],
        'city': 'Badr',
        'listing_type': 'buy',
        'price': '8,200,000 EGP',
        'imageUrl': 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&q=80&w=800',
        'title': 'Family House in Badr City',
        'description': 'Spacious family home in Badr City with a large garden and modern finishes.',
        'contactEmail': 'badr.office@realestate.eg',
        'contactPhone': '+20 122 345 6789',
        'bedrooms': 4,
        'bathrooms': 3,
        'area': '320 sqm',
        'year_built': 2018,
        'tags': ['private garden', 'parking']
    },
    {
        'id': 4,
        'location': [30.0571, 31.3415],
        'city': 'Nasr City',
        'listing_type': 'rent',
        'price': '25,000 EGP / Month',
        'imageUrl': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
        'title': 'Stylish Studio in Nasr City',
        'description': 'Newly renovated studio apartment in the heart of Nasr City. Ideal for young professionals.',
        'contactEmail': 'contact@nasr-homes.com',
        'contactPhone': '+20 106 555 4444',
        'bedrooms': 1,
        'bathrooms': 1,
        'area': '55 sqm',
        'year_built': 2023,
        'tags': ['smart home', 'air conditioner']
    }
]
